const $=s=>document.querySelector(s);
function select(group,button){document.querySelectorAll(group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}
const decipher=[
`<p class="label">A repeated name becomes a clue</p><div class="formula"><p><span data-name>Darius</span> · king · son of Hystaspes</p><p>Xerxes · king · son of <span data-name>Darius</span></p></div><button class="reveal" id="reveal-names" aria-pressed="false">Reveal the repeated name</button><p class="small" style="margin-top:15px">Simplified English model. Known royal family relationships helped scholars propose readings for unknown signs.</p>`,
`<h3>One royal account.<br>Three language versions.</h3><div class="flow"><strong class="from">Old Persian<small>First foothold</small></strong><span class="arrow" aria-hidden="true">→</span><strong>Elamite</strong><span class="arrow" aria-hidden="true">→</span><strong>Babylonian<small>Akkadian</small></strong></div><p>Match names and passages across versions. Use the better-understood text to test readings in the others.</p><p class="small">The versions are not exact word-for-word equivalents.</p>`,
`<p class="label">1857 · An independent check</p><h3>Four readers. One new inscription.</h3><div class="envelopes" aria-label="Four sealed translations"><span class="envelope">1</span><span class="envelope">2</span><span class="envelope">3</span><span class="envelope">4</span></div><button class="reveal" id="open-envelopes" aria-pressed="false">Compare the translations</button><p id="test-result" class="researchers" style="margin-top:12px">Hincks · Rawlinson · Oppert · Talbot</p>`];
function showDecipher(i){$('#decipher-evidence').innerHTML=decipher[i];$('#reveal-names')?.addEventListener('click',e=>{let on=e.currentTarget.getAttribute('aria-pressed')!=='true';document.querySelectorAll('[data-name]').forEach(n=>n.classList.toggle('matched',on));e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Hide the match':'Reveal the repeated name';});$('#open-envelopes')?.addEventListener('click',e=>{document.querySelectorAll('.envelope').forEach(n=>{n.classList.add('checked');n.textContent='✓';});e.currentTarget.setAttribute('aria-pressed','true');e.currentTarget.textContent='Translations compared';$('#test-result').textContent='They largely agreed. Independent readers could recover the same account—strong evidence that the method worked.';});}
document.querySelectorAll('[data-decipher]').forEach(b=>b.addEventListener('click',()=>{select('[data-decipher]',b);showDecipher(Number(b.dataset.decipher));}));showDecipher(0);
const features=[{title:'How much does the stroke lean?',text:'Compare the two circled letters on the right. Follow each descending stroke: its angle changes.',tip:'Angle is one feature. Look for repeated habits across a whole manuscript.',rects:[[2046,881,121,139],[2046,1020,121,139]]},{title:'How far does the base extend?',text:'Compare the two circled letters on the left. Look at the bottom stroke and how far it reaches.',tip:'A long or short base becomes useful when the pattern repeats.',rects:[[1610,881,120,139],[1610,1020,120,139]]},{title:'How tall? How wide?',text:'Compare the circled letters across the top row. Look at their width relative to their height.',tip:'These samples show variation. A difference alone does not tell us which is older.',rects:[[1610,881,120,139],[1900,881,120,139]]}];
function showFeature(i){let f=features[i];$('#feature-explanation').innerHTML=`<h3>${f.title}</h3><p>${f.text}</p><p class="callout">${f.tip}</p>`;$('#letter-marks').innerHTML=f.rects.map(([x,y,w,h],n)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="25" fill="none" stroke="${n?'#a26516':'#17657b'}" stroke-width="7"/>`).join('');}
document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{select('[data-feature]',b);showFeature(Number(b.dataset.feature));}));showFeature(0);
const examples={
creation:{ref:'Genesis 1:1–2:3 · Background before the flood',title:'The seventh day is set apart.',labels:['work','work','work','work','work','work','rest'],text:'Creation’s sequence reaches a blessed, holy seventh day. Here the text itself connects seven with completion and sacred time.',link:'https://bible.usccb.org/bible/genesis/2',linkText:'Read Genesis 2:1–3 ↗'},
animals:{ref:'Genesis 7:2–3',title:'Seven pairs = fourteen animals.',labels:['pair','pair','pair','pair','pair','pair','pair'],mode:'pairs',text:'Seven pairs of each kind of clean animal; birds also come in sevens of pairs. “Clean” is a religious category. Noah later offers clean animals in sacrifice (8:20).',link:'genesis.html#v-7-2',linkText:'Read the animal instructions →'},
dove:{ref:'Genesis 8:10–12',title:'Wait seven days. Send the dove.',labels:['1','2','3','4','5','6','7'],mode:'wait',text:'Two successive seven-day waits pace Noah’s testing: first the dove brings a leaf; after the next wait, it does not return.',link:'genesis.html#v-8-10',linkText:'Read the two waits →'},
storm:{ref:'Gilgamesh XI 128–131',title:'On the seventh day, the storm relents.',labels:['storm','storm','storm','storm','storm','storm','calm'],text:'Helle’s translation counts six days and seven nights of storm. The seventh day brings the change: a completed ordeal, then stillness.',link:'gilgamesh-xi.html#b-s39',linkText:'Read the end of the storm →'},
offering:{ref:'Gilgamesh XI 159–160',title:'Seven offering bowls, and seven more.',labels:['','','','','','',''],mode:'offering',text:'Two groups of seven organize Uta-napishti’s offering after the flood. Here the number shapes ritual action.',link:'gilgamesh-xi.html#b-s48',linkText:'Read the offering →'},
bread:{ref:'Gilgamesh XI · The sleep test',title:'Seven loaves make elapsed time visible.',labels:['oldest','','','','','','newest'],mode:'bread',text:'A loaf is set out each day as Gilgamesh sleeps. Their changing condition records the time he cannot account for: physical evidence that he failed the test.',link:'gilgamesh-xi.html#b-s66',linkText:'Read the evidence of the loaves →'}
};
function track(labels,cls='',pairs=false){return `<div class="seven-track ${cls}">${labels.map((l,i)=>`<div class="count-cell ${i===6?'last':''}" style="--age:${i+1}"><strong>${i+1}</strong>${pairs?'<span class="dots" aria-hidden="true"><i></i><i></i></span>':''}<small>${l||'&nbsp;'}</small></div>`).join('')}</div>`;}
function showSeven(key){let e=examples[key],visual=track(e.labels,e.mode==='bread'?'bread-track':e.mode==='pairs'?'pair-track':'',e.mode==='pairs');if(e.mode==='offering')visual=track(e.labels,'offering-track')+'<p class="label" style="margin:7px 0">+ Seven more</p>'+track(e.labels,'offering-track');if(e.mode==='wait')visual=track(['wait','wait','wait','wait','wait','wait','send'])+'<p class="mini-labels"><span>Seven-day wait → leaf</span><span>Seven more days → no return</span></p>';if(e.mode==='bread')visual+='<p class="small">Numbered tokens represent the loaves; color marks their order, not reconstructed appearance.</p>';$('#seven-evidence').innerHTML=`<p class="label">${e.ref}</p><h3>${e.title}</h3>${visual}<p class="interpretation">${e.text}</p><a href="${e.link}">${e.linkText}</a>`;}
document.querySelectorAll('[data-seven]').forEach(b=>b.addEventListener('click',()=>{select('[data-seven]',b);showSeven(b.dataset.seven);}));showSeven('creation');
