const $=s=>document.querySelector(s);
function select(group,button){document.querySelectorAll(group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}
const SEALS=[
{who:'Rawlinson',text:'Whoever shall abrade or injure my <mark class="k-tab">tablets</mark> and cylinders, or shall moisten them with <mark class="k-water">water</mark>, or scorch them with <mark class="k-fire">fire</mark>, or expose them to the air, or in the holy place of God shall assign them a position where they cannot be seen or understood, or who shall erase the writing and inscribe his own <mark class="k-name">name</mark>…'},
{who:'Talbot',text:'But He who my stone <mark class="k-tab">tablets</mark> and my memorial records shall injure, or shall destroy them: with <mark class="k-water">water</mark> shall efface them: or with <mark class="k-fire">fire</mark> shall consume them: or shall deface the writings: or shall write his <mark class="k-name">name</mark> (<i>instead of mine</i>)…'},
{who:'Hincks',text:'He who shall hide or obliterate my <mark class="k-tab">tablets</mark> and my floors shall wander on the <mark class="k-water">waters</mark>, shall be suspended in the <mark class="k-fire">fires</mark>, shall be besmeared with earth… and shall write his <mark class="k-name">name</mark> where some enemy shall speedily deface it…'},
{who:'Oppert',text:'He who hides or defaces my <mark class="k-tab">tablets</mark>, and my angular stones, who throws them into the <mark class="k-water">water</mark>, who burns them with <mark class="k-fire">fire</mark>, who spreads them to the winds… who engraves on them his <mark class="k-name">name</mark>…'}];
const decipher=[
`<p class="label">A repeated name becomes a clue</p><div class="formula"><p><span data-name>Darius</span> · king · son of Hystaspes</p><p>Xerxes · king · son of <span data-name>Darius</span></p></div><button class="reveal" id="reveal-names" aria-pressed="false">Reveal the repeated name</button><p class="small" style="margin-top:15px">Simplified English model. Known royal family relationships helped scholars propose readings for unknown signs.</p>`,
`<h3>One royal account.<br>Three language versions.</h3><div class="flow"><strong class="from">Old Persian<small>First foothold</small></strong><span class="arrow" aria-hidden="true">→</span><strong>Elamite</strong><span class="arrow" aria-hidden="true">→</span><strong>Babylonian<small>Akkadian</small></strong></div><p>Match names and passages across versions. Use the better-understood text to test readings in the others.</p><p class="small">The versions are not exact word-for-word equivalents.</p>`,
`<p class="label">1857 · The sealed test</p><h3>Four scholars. One inscription. No talking.</h3><p class="t-intro">A newly found inscription of the Assyrian king Tiglath-Pileser I went to four men separately. Each mailed back a translation in a sealed envelope. A committee opened all four together. Here is how each rendered the same curse on anyone who damages the king’s tablets.</p><button class="reveal" id="open-envelopes" aria-pressed="false">Break the seals</button><div class="seals" id="seals">`+SEALS.map(x=>`<article class="seal"><p class="who">${x.who}</p><p class="said">${x.text}</p></article>`).join('')+`</div><p class="t-verdict" id="t-verdict" hidden>Words for <mark class="k-water">water</mark>, <mark class="k-fire">fire</mark>, a <mark class="k-name">name</mark> written over the king’s, and the <mark class="k-tab">tablets</mark> turn up in all four. The committee reported “a very remarkable concurrence.” Look at Hincks, though: he read water and fire as punishments for the vandal, not damage to the tablets. They agreed on the signs and still argued about the grammar.</p><p class="small t-src">Paragraph LII, from <a href="https://www.digitale-sammlungen.de/en/view/bsb10250443?page=74,75" target="_blank" rel="noopener"><i>Inscription of Tiglath Pileser I, King of Assyria</i> (Royal Asiatic Society, 1857), pp. 70–71</a>. Public domain.</p>`];
function showDecipher(i){$('#decipher-evidence').innerHTML=decipher[i];$('#reveal-names')?.addEventListener('click',e=>{let on=e.currentTarget.getAttribute('aria-pressed')!=='true';document.querySelectorAll('[data-name]').forEach(n=>n.classList.toggle('matched',on));e.currentTarget.setAttribute('aria-pressed',String(on));e.currentTarget.textContent=on?'Hide the match':'Reveal the repeated name';});$('#open-envelopes')?.addEventListener('click',e=>{$('#seals').classList.add('open');$('#t-verdict').hidden=false;e.currentTarget.setAttribute('aria-pressed','true');e.currentTarget.textContent='Seals broken';e.currentTarget.disabled=true;});}
document.querySelectorAll('[data-decipher]').forEach(b=>b.addEventListener('click',()=>{select('[data-decipher]',b);showDecipher(Number(b.dataset.decipher));}));showDecipher(0);
const features=[{title:'How much does the stroke lean?',text:'Compare the two circled letters on the right. Follow each descending stroke: its angle changes.',tip:'Angle is one feature. Look for repeated habits across a whole manuscript.',rects:[[2046,881,121,139],[2046,1020,121,139]]},{title:'How far does the base extend?',text:'Compare the two circled letters on the left. Look at the bottom stroke and how far it reaches.',tip:'A long or short base becomes useful when the pattern repeats.',rects:[[1610,881,120,139],[1610,1020,120,139]]},{title:'How tall? How wide?',text:'Compare the circled letters across the top row. Look at their width relative to their height.',tip:'These samples show variation. A difference alone does not tell us which is older.',rects:[[1610,881,120,139],[1900,881,120,139]]}];
function showFeature(i){let f=features[i];$('#feature-explanation').innerHTML=`<h3>${f.title}</h3><p>${f.text}</p><p class="callout">${f.tip}</p>`;$('#letter-marks').innerHTML=f.rects.map(([x,y,w,h],n)=>`<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="25" fill="none" stroke="${n?'#a26516':'#17657b'}" stroke-width="7"/>`).join('');}
document.querySelectorAll('[data-feature]').forEach(b=>b.addEventListener('click',()=>{select('[data-feature]',b);showFeature(Number(b.dataset.feature));}));showFeature(0);
const examples={
creation:{ref:'Genesis 1:1–2:3 · Background before the flood',title:'The seventh day is set apart.',labels:['work','work','work','work','work','work','rest'],text:'Creation’s sequence reaches a blessed, holy seventh day. Here the text itself connects seven with completion and sacred time.',link:'https://bible.usccb.org/bible/genesis/2',linkText:'Read Genesis 2:1–3 ↗'},
animals:{ref:'Genesis 7:2–3',title:'Seven pairs = fourteen animals.',labels:['pair','pair','pair','pair','pair','pair','pair'],mode:'pairs',text:'Seven pairs of each kind of clean animal; birds also come in sevens of pairs. “Clean” is a religious category. Noah later offers clean animals in sacrifice (8:20).',link:'genesis.html#v-7-2',linkText:'Read the animal instructions →'},
dove:{ref:'Genesis 8:10–12',title:'Wait seven days. Send the dove.',labels:['1','2','3','4','5','6','7'],mode:'wait',text:'Two successive seven-day waits pace Noah’s testing: first the dove brings a leaf; after the next wait, it does not return.',link:'genesis.html#v-8-10',linkText:'Read the two waits →'},
storm:{ref:'Gilgamesh XI 128–131',title:'On the seventh day, the storm relents.',labels:['storm','storm','storm','storm','storm','storm','calm'],text:'Helle’s translation counts six days and seven nights of storm. The seventh day brings the change: a completed ordeal, then stillness.',link:'gilgamesh-xi.html#b-s39',linkText:'Read the end of the storm →'},
offering:{ref:'Gilgamesh XI 159–160',title:'Seven offering bowls, and seven more.',labels:['','','','','','',''],mode:'offering',text:'Two groups of seven organize Uta-napishti’s offering after the flood. Here the number shapes ritual action.',link:'gilgamesh-xi.html#b-s48',linkText:'Read the offering →'},
bread:{ref:'Gilgamesh XI · The sleep test',title:'Seven loaves make elapsed time visible.',labels:['oldest','','','','','','newest'],mode:'bread',text:'A loaf is set out each day as Gilgamesh sleeps. Their changing condition records the time he cannot account for: physical evidence that he failed the test.',link:'gilgamesh-xi.html#b-s66',linkText:'Read the evidence of the loaves →'}
};
function track(labels,cls='',pairs=false){return `<div class="seven-track ${cls}">${labels.map((l,i)=>`<div class="count-cell ${i===6?'last':''}" style="--age:${i+1}"><strong>${i+1}</strong>${pairs?'<span class="dots" aria-hidden="true"><i></i><i></i></span>':''}<small>${l||'&nbsp;'}</small></div>`).join('')}</div>`;}
function showSeven(key){let e=examples[key],visual=track(e.labels,e.mode==='bread'?'bread-track':e.mode==='pairs'?'pair-track':'',e.mode==='pairs');if(e.mode==='offering')visual=track(e.labels,'offering-track')+'<p class="label" style="margin:7px 0">+ Seven more</p>'+track(e.labels,'offering-track');if(e.mode==='wait')visual=track(['wait','wait','wait','wait','wait','wait','send'])+'<p class="mini-labels"><span>Seven-day wait → leaf</span><span>Seven more days → no return</span></p>';if(e.mode==='bread')visual+='<p class="small">Numbered tokens represent the loaves; color marks their order, not reconstructed appearance.</p>';$('#seven-evidence').innerHTML=`<p class="label">${e.ref}</p><h3>${e.title}</h3>${visual}<p class="interpretation">${e.text}</p><a href="${e.link}">${e.linkText}</a>`;}
document.querySelectorAll('[data-seven]').forEach(b=>b.addEventListener('click',()=>{select('[data-seven]',b);showSeven(b.dataset.seven);}));showSeven('creation');
// base 60: long division of 1 by n, digit by digit, spotting the repeat
function sixtieths(n){let r=1,seen={},digits=[];while(r&&!(r in seen)&&digits.length<12){seen[r]=digits.length;r*=60;digits.push(Math.floor(r/n));r%=n;}return {digits,repeat:r?seen[r]:null};}
function showBase(n){const {digits,repeat}=sixtieths(n);let html='';
 if(repeat===null){html=`<p class="frac">1/${n}</p><p class="digits even">${digits.join(', ')} <span>sixtieths${digits.length>1?' and smaller':''}</span></p><p class="verdict ok">Comes out even.</p>`;}
 else{const cyc=digits.slice(repeat);html=`<p class="frac">1/${n}</p><p class="digits never">${cyc.concat(cyc,cyc).map((d,i)=>`<b style="--i:${i}">${d}</b>`).join(', ')}, …</p><p class="verdict no">Never comes out even. The same three numbers repeat forever.</p>`;}
 $('#base60-out').innerHTML=html;}
document.querySelectorAll('[data-div]').forEach(b=>b.addEventListener('click',()=>{select('[data-div]',b);showBase(Number(b.dataset.div));}));showBase(7);
