const $=s=>document.querySelector(s);
function select(group,button){document.querySelectorAll(group).forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}
const examples={
creation:{ref:'Genesis 1:1–2:3 · Background before the flood',title:'The seventh day is set apart.',labels:['work','work','work','work','work','work','rest'],text:'Creation’s sequence reaches a blessed, holy seventh day. Here the text itself connects seven with completion and sacred time.',link:'https://bible.usccb.org/bible/genesis/2',linkText:'Read Genesis 2:1–3 ↗'},
animals:{ref:'Genesis 7:2–3',title:'Seven pairs = fourteen animals.',labels:['pair','pair','pair','pair','pair','pair','pair'],mode:'pairs',text:'Seven pairs of each kind of clean animal; birds also come in sevens of pairs. “Clean” is a religious category. Noah later offers clean animals in sacrifice (8:20).',link:'genesis.html#v-7-2',linkText:'Read the animal instructions →'},
dove:{ref:'Genesis 8:10–12',title:'Wait seven days. Send the dove.',labels:['1','2','3','4','5','6','7'],mode:'wait',text:'Two successive seven-day waits pace Noah’s testing: first the dove brings a leaf; after the next wait, it does not return.',link:'genesis.html#v-8-10',linkText:'Read the two waits →'},
storm:{ref:'Gilgamesh XI 128–131',title:'On the seventh day, the storm relents.',labels:['storm','storm','storm','storm','storm','storm','calm'],text:'Helle’s translation counts six days and seven nights of storm. The seventh day brings the change: a completed ordeal, then stillness.',link:'gilgamesh-xi.html#b-s39',linkText:'Read the end of the storm →'},
offering:{ref:'Gilgamesh XI 159–160',title:'Seven offering bowls, and seven more.',labels:['','','','','','',''],mode:'offering',text:'Two groups of seven organize Uta-napishti’s offering after the flood. Here the number shapes ritual action.',link:'gilgamesh-xi.html#b-s48',linkText:'Read the offering →'},
bread:{ref:'Gilgamesh XI · The sleep test',title:'Seven loaves make elapsed time visible.',labels:['oldest','','','','','','newest'],mode:'bread',text:'A loaf is set out each day as Gilgamesh sleeps. Their changing condition records the time he cannot account for: physical evidence that he failed the test.',link:'gilgamesh-xi.html#b-s66',linkText:'Read the evidence of the loaves →'}
};
function track(labels,cls='',pairs=false){return `<div class="seven-track ${cls}">${labels.map((l,i)=>`<div class="count-cell ${i===6?'last':''}" style="--age:${i+1}"><strong>${i+1}</strong>${pairs?'<span class="dots" aria-hidden="true"><i></i><i></i></span>':''}<small>${l||'&nbsp;'}</small></div>`).join('')}</div>`;}
function showSeven(key){let e=examples[key],visual=track(e.labels,e.mode==='bread'?'bread-track':e.mode==='pairs'?'pair-track':'',e.mode==='pairs');if(e.mode==='offering')visual=track(e.labels,'offering-track')+'<p class="label" style="margin:7px 0">+ Seven more</p>'+track(e.labels,'offering-track');if(e.mode==='wait')visual=track(['wait','wait','wait','wait','wait','wait','send'])+'<p class="mini-labels"><span>Seven-day wait → leaf</span><span>Seven more days → no return</span></p>';if(e.mode==='bread')visual+='<p class="small">Numbered tokens represent the loaves; color marks their order, not reconstructed appearance.</p>';$('#seven-evidence').innerHTML=`<p class="label">${e.ref}</p><h3>${e.title}</h3>${visual}<p class="interpretation">${e.text}</p><a href="${e.link}">${e.linkText}</a>`;}
document.querySelectorAll('[data-seven]').forEach(b=>b.addEventListener('click',()=>{select('[data-seven]',b);showSeven(b.dataset.seven);}));showSeven('creation');

// base 60: long division of 1 by n, digit by digit, spotting the repeat
function sixtieths(n){let r=1,seen={},digits=[];while(r&&!(r in seen)&&digits.length<12){seen[r]=digits.length;r*=60;digits.push(Math.floor(r/n));r%=n;}return {digits,repeat:r?seen[r]:null};}
function showBase(n){const {digits,repeat}=sixtieths(n);let html='';
 if(repeat===null){html=`<p class="frac">1/${n}</p><p class="digits even">${digits.join(', ')} <span>sixtieths${digits.length>1?' and smaller':''}</span></p><p class="verdict ok">Comes out even.</p>`;}
 else{const cyc=digits.slice(repeat);html=`<p class="frac">1/${n}</p><p class="digits never">${cyc.concat(cyc,cyc).map((d,i)=>`<b style="--i:${i}">${d}</b>`).join(', ')}, …</p><p class="verdict no">Never comes out even. The same three numbers repeat forever.</p>`;}
 $('#base60-out').innerHTML=html;}
document.querySelectorAll('[data-div]').forEach(b=>b.addEventListener('click',()=>{select('[data-div]',b);showBase(Number(b.dataset.div));}));showBase(7);
