#!/usr/bin/env python3
"""Build the October 5 class resource from public-safe reading data and sourced map markup."""
import html,json
from pathlib import Path
from blood_dazzler_word_graph import render_graph
ROOT=Path(__file__).resolve().parent.parent
ASSETS=ROOT/'frst-110-resources/blood-dazzler-assets'
e=html.escape
c=json.loads((ASSETS/'reading-data.json').read_text())
rows=lambda data: ''.join(f'<tr><td><strong>{e(x["name"])}</strong></td><td>{e(x["pages"])}</td><td>{e(x["role"])}</td></tr>' for x in data)
word_graph=render_graph(json.loads((ASSETS/'word-connections.json').read_text()))
tasks=''.join(f'<article class="task"><h3>{e(x["title"])}</h3><p>Book: pp. {e(x["pages"])}</p><ol>'+''.join(f'<li>{e(s)}</li>' for s in x['steps'])+'</ol></article>' for x in c['discussion'])
poems=''.join(f'<tr><td>{e(x["pages"])}</td><td>{e(x["title"])}</td><td>{e(x["voice"])}</td></tr>' for x in c['poems'])
map_html=(ASSETS/'map-fragment.html').read_text().replace('<section class="bd-map"','<section id="map" class="bd-map"',1)
page=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Blood Dazzler · October 5 · FRST 110</title><meta name="description" content="Patricia Smith, pp. vii–24: New Orleans map, rooftop rescue photographs and helicopter footage, word connections, characters, and poem voices.">
<link rel="icon" href="../favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../_kit/vendor/leaflet/leaflet.css"><link rel="stylesheet" href="../_kit/blood-dazzler-1.css"><link rel="stylesheet" href="../_kit/blood-dazzler-map.css"><link rel="stylesheet" href="../_kit/blood-dazzler-words.css">
<meta property="og:title" content="Blood Dazzler · October 5"><meta property="og:description" content="New Orleans geography, rooftop waiting and rescue, and Patricia Smith’s opening poems, pp. vii–24."><meta property="og:type" content="website"><meta property="og:url" content="https://omatty123.github.io/teaching-fall-2026/frst-110-resources/blood-dazzler-oct-5.html"><meta property="og:image" content="https://omatty123.github.io/teaching-fall-2026/frst-110-resources/blood-dazzler-assets/rooftop-waiting.jpg"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:image" content="https://omatty123.github.io/teaching-fall-2026/frst-110-resources/blood-dazzler-assets/rooftop-waiting.jpg">
</head><body><a class="skip" href="#content">Skip to reading materials</a>
<nav class="nav" aria-label="Breadcrumb"><div class="nav-inner"><a class="brand" href="../courses/frst-110.html">FRST 110</a><a class="crumb" href="../courses/frst-110.html">Course materials</a><a href="https://lawrence.instructure.com/courses/14726/pages/song-of-the-day-the-river-in-reverse-elvis-costello-and-allen-toussaint">The River in Reverse</a></div></nav>
<main id="content"><header><h1>Blood Dazzler</h1><p class="meta">Patricia Smith · Monday, October 5, 2026 · pp. vii–24</p>
<nav class="section-nav" aria-label="Page sections"><a href="#map">New Orleans map</a><a href="#photographs">Rooftop photographs</a><a href="#video">Helicopter rescue</a><a href="#words">Word connections</a><a href="#characters">Characters</a><a href="#poems">Poem voices</a><a href="#discussion">Discussion</a></nav></header>
{map_html}
<section id="photographs"><h2>People waiting on roofs</h2><div class="photos">
<figure><a href="blood-dazzler-assets/rooftop-waiting.jpg" target="_blank" rel="noopener" aria-label="Open the full FEMA rooftop photograph"><img src="blood-dazzler-assets/rooftop-waiting.jpg" width="1800" height="1173" loading="lazy" alt="Two people sit on the roof of a house surrounded by deep floodwater and damaged buildings in New Orleans."></a><figcaption><strong>New Orleans, August 30, 2005.</strong> Two people wait on a roof surrounded by floodwater.<span class="credit">Jocelyn Augustino / FEMA · Public domain · <a href="https://commons.wikimedia.org/wiki/File:Katrina-14512.jpg">FEMA photograph 14512 and original caption</a></span></figcaption></figure>
<figure><a href="blood-dazzler-assets/rooftop-before-hoist.jpg" target="_blank" rel="noopener" aria-label="Open the full Coast Guard rooftop photograph"><img src="blood-dazzler-assets/rooftop-before-hoist.jpg" width="1000" height="750" loading="lazy" alt="Four survivors sit on a sloping roof with a Coast Guard rescue swimmer preparing a hoist."></a><figcaption><strong>New Orleans, September 7, 2005.</strong> Four survivors and a Coast Guard rescue swimmer prepare for a hoist.<span class="credit">Lt. Kevin d’Eustachio / U.S. Coast Guard · Public domain · <a href="https://www.dvidshub.net/image/1077965">Official photograph and caption</a></span></figcaption></figure>
</div><p class="note" style="margin-top:14px">Read “Up on the Roof,” p. 23. Describe what each photograph shows, then identify what the poem supplies that the photograph cannot establish. The photographs do not identify the poem’s unnamed survivor.</p></section>
<section id="video"><h2>Helicopter rescue in New Orleans</h2><div class="media-layout"><figure>
<video controls playsinline preload="metadata" poster="blood-dazzler-assets/rescue-poster.jpg" aria-label="Rescue Helicopters Over New Orleans, September 12, 2005" aria-describedby="video-caption"><source src="blood-dazzler-assets/helicopter-rescue.mp4" type="video/mp4"><track kind="descriptions" src="blood-dazzler-assets/rescue-descriptions.vtt" srclang="en" label="English visual descriptions"><p><a href="https://www.dvidshub.net/video/5776/rescue-helicopters-over-new-orleans">Watch the official rescue footage on DVIDS</a>.</p></video>
<figcaption id="video-caption"><strong>Rescue Helicopters Over New Orleans · 1 minute 22 seconds.</strong><span class="credit">September 12, 2005 · 1st Combat Camera Squadron · Public domain · <a href="https://www.dvidshub.net/video/5776/rescue-helicopters-over-new-orleans">Official footage and source record</a></span></figcaption>
<details><summary>Visual description of the footage</summary><div><p>The camera looks down from a helicopter over flooded streets and rooftops. People wait on a roof; a crew member and hoist line appear in the foreground. In the final part, a rescue swimmer and survivor rise toward the helicopter, and the crew brings the survivor through the open door.</p><p class="note">These descriptions identify visible actions; they do not transcribe dialogue.</p></div></details></figure>
<aside class="reading-task"><h3>“Up on the Roof” · p. 23</h3><ol><li>Identify the camera’s position and the survivor’s position.</li><li>Find where aircraft noise interferes with speech in the poem.</li><li>Explain how the poem’s “you” changes your position compared with the video camera.</li><li>Read the poem’s last two lines. Explain what remains uncertain about the survivor’s choice.</li></ol><p class="note">This clip documents a later rescue, on September 12. It gives context for the actions in the poem; it does not record the poem’s particular scene.</p></aside></div></section>
{word_graph}
<section id="characters"><h2>Explicit characters</h2><p>Explicit characters are named or directly described. They can be unnamed people, groups, animals, religious figures, or personified places and weather.</p><p><strong>New Orleans and Katrina are different female figures.</strong> Keep the city’s voice separate from the storm’s voice, and keep the unnamed residents separate from one another.</p><table class="character-table"><thead><tr><th scope="col">Character</th><th scope="col">Pages</th><th scope="col">What the text establishes</th></tr></thead><tbody>{rows(c['characters']['explicit'])}</tbody></table>
<h2 style="margin-top:30px">Implicit characters</h2><p>These are people or groups inferred from the poems. The identifications below are interpretations.</p><table class="character-table"><thead><tr><th scope="col">Implied figure</th><th scope="col">Pages</th><th scope="col">Evidence for the inference</th></tr></thead><tbody>{rows(c['characters']['implicit'])}</tbody></table></section>
<section id="poems"><h2>Who speaks in each poem?</h2><p class="note">Page numbers are printed book pages. A narrator describing someone’s experience is different from that person speaking directly.</p><table class="poem-table"><thead><tr><th scope="col">Pages</th><th scope="col">Poem</th><th scope="col">Voice or perspective</th></tr></thead><tbody>{poems}</tbody></table></section>
<section id="discussion"><h2>Discussion</h2><div class="tasks">{tasks}</div></section>
<footer><p>{e(c['source_note'])} Read the complete poems in your book.</p><p>Historical photographs and footage retain their dates and source credits. The map uses modern geographic context. <a href="blood-dazzler-assets/SOURCES.md">Source and method record</a> · <a href="../courses/frst-110.html">FRST 110 course materials</a></p></footer></main>
<script src="../_kit/vendor/leaflet/leaflet.js"></script><script src="../_kit/blood-dazzler-map.js"></script><script src="../_kit/blood-dazzler-words.js"></script>
</body></html>'''
(ROOT/'frst-110-resources/blood-dazzler-oct-5.html').write_text(page)
print('Built Blood Dazzler Oct5: 22 poems, pp. vii–24.')
